[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quant_options_mm"
version = "0.1"
dependencies = []

[tool.setuptools]
packages = { find = { where = ["src"] } }
