name: CI - Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: quant-mm
          environment-file: environment.yml  # Use environment.yml directly
          cache-environment: true

      - name: Run unit tests
        run: micromamba run -n quant-mm pytest tests/
